var constants = {
  MOVE_TO_ACTIVE:   'MOVE_TO_ACTIVE',
  MOVE_TO_INACTIVE: 'MOVE_TO_INACTIVE',
  RECORD_OFFENSE:   'RECORD_OFFENSE',
  RECORD_DEFENSE:   'RECORD_DEFENSE'
}

module.exports = constants;
